name: CI

on:
  push:
  pull_request:

jobs:
  format-test:
    name: Format
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install clang-format
        run: sudo apt install clang-format
      
      - name: Format
        run:
          find ./src ./test -regex '.*\.hpp' -exec clang-format -style=file -i {} \;
      
      - name: Compare
        run: test -z "$(git diff)"
  
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        
      - name: Install clang
        run: sudo apt install clang

      - name: Build test
        run: clang++ -std=gnu++17 -O2 test/main.cpp -I src/ -o test/main
      
      - name: Run test
        run: |
          ulimit -s unlimited
          test/main
